build_platform:
  linux_64: linux_64
  # skip building x64
  #   Undefined symbols for architecture x86_64:
  #       "_getentropy", referenced from:
  #   ld: symbol(s) not found for architecture x86_64
  #osx_64: osx_64
  osx_arm64: osx_arm64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
